// <auto-generated />
using System;
using ClientesApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ClientesApp.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200724004021_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ClientesApp.API.Models.Cliente", b =>
                {
                    b.Property<int>("ID_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EstadoCivilID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_Nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Genero")
                        .HasColumnType("bit");

                    b.Property<string>("Identificacion")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .HasColumnType("varchar(150)");

                    b.HasKey("ID_Cliente");

                    b.HasIndex("EstadoCivilID");

                    b.HasIndex("Identificacion")
                        .IsUnique()
                        .HasFilter("[Identificacion] IS NOT NULL");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ClientesApp.API.Models.EstadoCivil", b =>
                {
                    b.Property<int>("EstadoCivilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstadoCivilID");

                    b.ToTable("EstadosCiviles");
                });

            modelBuilder.Entity("ClientesApp.API.Models.Cliente", b =>
                {
                    b.HasOne("ClientesApp.API.Models.EstadoCivil", "EstadoCivil")
                        .WithMany("Clientes")
                        .HasForeignKey("EstadoCivilID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
